### GET request
GET http://localhost:3000/plants

### POST request
POST http://localhost:3000/plants
Accept: application/json
Content-Type: application/json

{
  "imgSrc": "https://commons.wikimedia.org/wiki/File:Oxalis_triangularis6.jpg",
  "family": "Oxalidaceae",
  "genus": "Oxalis",
  "species": "triangularis",
  "common": ["False Shamrock", "Purple Shamrock Plant", "Love Plant"],
  "water": "0",
  "light": "0",
  "humidity": "0",
  "tempLow": "0",
  "tempHigh": "0",
  "tags": ["testing"],
  "text": "KENPEI, CC BY-SA 3.0 <http://creativecommons.org/licenses/by-sa/3.0/>, via Wikimedia Commons"
}

### PUT request
PUT http://localhost:3000/plants
Accept: application/json
Content-Type: application/json

{
  "id": "66f8a8e0f921bc1e21e7d264",
  "family": "Araceae",
  "imgSrc": "https://upload.wikimedia.org/wikipedia/commons/6/62/Money_Plant_%28Epipremnum_aureum%29_4.jpg",
  "text": "Mokkie, CC BY-SA 3.0 <https://creativecommons.org/licenses/by-sa/3.0>, via Wikimedia Commons"
}

### DELETE request
DELETE http://localhost:3000/plants
Accept: application/json
Content-Type: application/json

{
  "id": "66f79b75af3163d38c11f84e"
}

### GET a single Plant
GET http://localhost:3000/plants/id/66fa4961a8f6f95cf46019d8
Accept: application/json
Content-Type: application/json

{
  "_id": "66f756622d158ddbe8849c42"
}

### GET a plant search
GET http://localhost:3000/plants/search/common=%25botanical=monstera%20
Accept: application/json
Content-Type: application/json

###