### GET request
GET http://localhost:3000/plants

### POST request
POST http://localhost:3000/plants
Accept: application/json
Content-Type: application/json

{
  "imgSrc": "img/PlantDB/ceropegia-woodii.jpg",
  "family": "Apocynaceae",
  "genus": "Ceropegia",
  "species": "woodii",
  "common": ["String of Hearts", "Hearts on a String", "Rosary Plant", "Sweetheart Vine", "Chain of Hearts"],
  "water": "Allow Time to Dry Inbetween",
  "light": "Full Sun",
  "humidity": "",
  "tempLow": "8",
  "tempHigh": "30",
  "tags": ["succulent"],
  "text": "<p>Named for their iconic leaves, the String of Hearts is a well liked succulent and is a popular choice for hanging baskets and pots. In the warmer months, the plant produces small, tubular flowers.</p><p>These plants will quickly rot if left in wet substrate for too long, and are susceptible to spider mites and mealybugs.</p><p>Image From:<br><a href='https://unsplash.com/photos/person-holding-green-plant-on-gray-pot-8FqkmqrWD6E'>feey. (2021). <i>A man holding a String of Hearts plant</i> [Photograph]. Unsplash. https://unsplash.com/photos/person-holding-green-plant-on-gray-pot-8FqkmqrWD6E</a></p>"
}

### PUT request
PUT http://localhost:3000/plants
Accept: application/json
Content-Type: application/json

{
  "id": "66f8a8e0f921bc1e21e7d264",
  "water": "Allow Time to Dry Inbetween",
  "light": "Light Shade",
  "humidity": "Low",
  "tempLow":15,
  "tempHigh":24,
  "tags": [
    "foliage",
    "hanging"
  ]
}

### DELETE request
DELETE http://localhost:3000/plants
Accept: application/json
Content-Type: application/json

{
  "id": "66f79b75af3163d38c11f84e"
}

### GET a single Plant
GET http://localhost:3000/plants/id/66fa4961a8f6f95cf46019d8
Accept: application/json
Content-Type: application/json

### GET a plant search
GET http://localhost:3000/plants/search/common=%25botanical=%25family=%25water=%25light=%25humidity=Low
Accept: application/json
Content-Type: application/json

###