### POST request
POST http://localhost:3000/plants
Accept: application/json
Content-Type: application/json

{ "family": "Araceae",
  "genus": "Monstera",
  "species": "deliciosa",
  "common": ["Swiss Cheese Plant", "Fruit Salad Plant", "Ceriman"]
}
###