### GET request
GET http://localhost:3000/problems
Accept: application/json
Content-Type: application/json

### POST request
POST http://localhost:3000/problems
Accept: application/json
Content-Type: application/json

{
  "imgSrc": "https://upload.wikimedia.org/wikipedia/commons/8/88/Aphids_May_2010-2.jpg",
  "common": ["Aphids", "Greenfly", "Blackfly", "Whitefly"],
  "scientific": "Aphididae Species",
  "category": "pest",
  "leafTags": ["insect (pale-green)", "substance-sticky", "curled"],
  "flowerTags": ["substance-sticky"],
  "stemTags": ["substance-sticky"],
  "rootTags": [""],
  "wholeTags": [""],
  "growthTags": ["slow"],
  "treatment": "<ul><li>Aphids tend to be on stems, flowerbuds, and the undersides of leaves. Wear plastic gloves then give them a light squeeze and wipe them off the plant to remove them.</li><li>Biological control can work in some cases.</li><li>Spraying with diluted neem oil or horticultural soap after the above process can help kill any remaining aphids, though this is not necessary.</li><li>It can be a good idea to remove parts of the plant with dense populations, or bin the plant entirely if it is heavily infested.</li></ul>",
  "information": "There are over 5000 different species of aphids across the world, and they are typically 1-7mm in length. They gather predominately on the tips of the stems and new growth of the plant.<br>All life stages of the Aphid secrete honeydew, a sticky substance which can lead to Sooty Mould.<br><br>Image from:<a href='https://commons.wikimedia.org/wiki/File:Aphids_May_2010-2.jpg' class='reference'>Alvesgaspar. (2010). Aphids May 2010-2.jpg [Photograph]. Wikimedia Commons. https://commons.wikimedia.org/wiki/File:Aphids_May_2010-2.jpg"
}

### PUT request
PUT http://localhost:3000/problems
Accept: application/json
Content-Type: application/json

{
  "id": "66f8a8e0f921bc1e21e7d264"
}

### DELETE request
DELETE http://localhost:3000/problems
Accept: application/json
Content-Type: application/json

{
  "id": "66fe3533ad28d4f96257b3cf"
}

### GET a single Problem
GET http://localhost:3000/problems/id/
Accept: application/json
Content-Type: application/json

{
  "_id": "66f756622d158ddbe8849c42"
}

### GET all category
GET http://localhost:3000/problems/pest
Accept: application/json
Content-Type: application/json

###