### GET request
GET http://localhost:3000/problems
Accept: application/json
Content-Type: application/json

### POST request
POST http://localhost:3000/problems
Accept: application/json
Content-Type: application/json

{
  "imgSrc": "",
  "common": ["Corky Scab"],
  "scientific": "",
  "category": "disease",
  "leafTags": ["scab"],
  "flowerTags": [""],
  "stemTags": [""],
  "rootTags": [""],
  "wholeTags": [""],
  "growthTags": [""],
  "treatment": "<ul><li>These scabs are not fatal, but rather an indication that the affected cactus is suffering from poor conditions.</li><li>Reduce watering and feeding, and increase the air circulation to reduce hummidity.</li></ul>",
  "information": "These light brown scabs tend to appear on the surface of cacti. While they will not dirrectly damage the plant, they can be an indicator of a plant that is either overfed, overwatered, too humid, or all three."
}

### PUT request
PUT http://localhost:3000/problems
Accept: application/json
Content-Type: application/json

{
  "id": "66fe4e7d35a7baa560a90fde",
  "information": "There are over 5000 different species of aphids across the world, and they are typically 1-7mm in length. They gather predominately on the tips of the stems and new growth of the plant.<br>All life stages of the Aphid secrete honeydew, a sticky substance which can lead to Sooty Mould.<br><br>Image from:<a href='https://commons.wikimedia.org/wiki/File:Aphids_May_2010-2.jpg' class='reference'>Alvesgaspar. (2010). Aphids May 2010-2.jpg [Photograph]. Wikimedia Commons. https://commons.wikimedia.org/wiki/File:Aphids_May_2010-2.jpg</a>"
}

### DELETE request
DELETE http://localhost:3000/problems
Accept: application/json
Content-Type: application/json

{
  "id": "66fe3533ad28d4f96257b3cf"
}

### GET a single Problem
GET http://localhost:3000/problems/id/66fe4e7d35a7baa560a90fde
Accept: application/json
Content-Type: application/json

### GET all category
GET http://localhost:3000/problems/pest
Accept: application/json
Content-Type: application/json

###

### GET search
GET http://localhost:3000/problems/search/category=all%25name=root%20aphid
Accept: application/json
Content-Type: application/json

###