### GET request
GET http://localhost:3000/problems
Accept: application/json
Content-Type: application/json

### POST request
POST http://localhost:3000/problems
Accept: application/json
Content-Type: application/json

{
  "imgSrc": "",
  "common": ["Underwatering"],
  "scientific": "",
  "category": "care",
  "leafTags": ["leaf-brown", "leaf-yellow", "leaf-red", "curled"],
  "flowerTags": ["drop"],
  "stemTags": [""],
  "rootTags": [""],
  "wholeTags": ["wilt"],
  "growthTags": ["slow"],
  "treatment": "<ul><li>There are a few methods for helping a severly underwatered plant.</li><li>Firstly, you should confirm that the plant isn't rootbound, as this can affect the plant's ability to take in both water and nutrients.</li><li>For very dry compost, you can place the plant in a shallow dish of water and wait until the top of the compost is glistening with water - this allows the compost to gradually remoisten with a lower risk of waterlogging the plant.</li><li>Of course, the easiest is to water your plant and give it a good drink.</li></ul>",
  "information": "Underwatering can affect all plants, regardless of how little water they appear to need. Yes, even the cacti and other plants adapted to arid environments."
}

### PUT request
PUT http://localhost:3000/problems
Accept: application/json
Content-Type: application/json

{
  "id": "66f8a8e0f921bc1e21e7d264"
}

### DELETE request
DELETE http://localhost:3000/problems
Accept: application/json
Content-Type: application/json

{
  "id": "66fe3533ad28d4f96257b3cf"
}

### GET a single Problem
GET http://localhost:3000/problems/id/
Accept: application/json
Content-Type: application/json

{
  "_id": "66f756622d158ddbe8849c42"
}

### GET all category
GET http://localhost:3000/problems/pest
Accept: application/json
Content-Type: application/json

###